eval:
  save_dir: results
parent_dir: NIAH/Needle_test
pred:
  model_path: /Users/felix_admin/.cache/kagglehub/models/google/recurrentgemma/PyTorch/2b/1/2b.pt
  save_dir: pred
  sparsification:
    k:
    - 10
    metric: l2
    prefill: true
  tokenizer_path: /Users/felix_admin/.cache/kagglehub/models/google/recurrentgemma/PyTorch/2b/1/tokenizer.model
prompt:
  context:
    interval: 10
    manually_select_list: null
    max_len: 4096
    min_len: 250
  document_depth:
    interval: 10
    interval_type: linear
    manually_select_list: null
    max_percent: 100
    min_percent: 0
  haystack_dir: PaulGrahamEssays
  needle: '

    The best thing to do in San Francisco is eat a sandwich and sit in Dolores Park
    on a sunny day.

    '
  retrieval_question: 'What is the best thing to do in San Francisco? Here is the
    most relevant sentence in the context:'
  save_dir: prompts
  tokenizer:
    model_name: "google/recurrentgemma-2b"
    tokenizer_type: Huggingface
vis:
  save_dir: vis
