#configpred.yaml
prompt_dir: 'LongAlign/Needle_test/prompts'
kaggle_model_path: "/root/.cache/kagglehub/models/google/recurrentgemma/PyTorch/2b/1/2b.pt"
save_dir: 'LongAlign/Needle_test/pred'
sparsification:
  sparsify: True
  k: [10]
  metric: "l2"
  prefill: True
model:
  model_provider: "Huggingface"  # "OpenAI", "Anthropic" or "Huggingface"
  model_name: "models/recurrent_gemma_default"
needle:
  needle: " best thing to do in San Francisco is eat a sandwich and sit in Dolores Park on a sunny day"
  focus: True
  scaling: 1.0
