eval:
  save_dir: 9B/results_jrt
parent_dir: NIAH/Needle_test/RG/
pred:
  is_jrt: true
  model_path: /scratch/project/eu-25-48/.cache/kagglehub/models/google/recurrentgemma/PyTorch/9b/2/9b.pt
  save_dir: 9B/pred_jrt
  sparsification:
    k:
    - 1
    - 2
    metric: entropy
    prefill: false
  tokenizer_path: /scratch/project/eu-25-48/.cache/kagglehub/models/google/recurrentgemma/PyTorch/9b/2/tokenizer.model
prompt:
  context:
    interval: 10
    manually_select_list: null
    max_len: 4096
    min_len: 250
  document_depth:
    interval: 10
    interval_type: linear
    manually_select_list: null
    max_percent: 100
    min_percent: 0
  haystack_dir: ../PaulGrahamEssays
  is_base: true
  is_jrt: true
  needle: '

    The best thing to do in San Francisco is eat a sandwich and sit in Dolores Park
    on a sunny day.

    '
  retrieval_question: What is the best thing to do in San Francisco?
  save_dir: prompts_base_jrt
  tokenizer:
    model_name: google/recurrentgemma-9b
    tokenizer_type: Huggingface
vis:
  save_dir: 9B/vis_jrt
