#configpred.yaml
prompt_dir: 'LongAlign/Needle_test/prompts'
save_dir: 'LongAlign/Needle_test/pred'
k: [0,1,2,3,4,5,6,7,8,9]
model:
  model_provider: "Huggingface"  # "OpenAI", "Anthropic" or "Huggingface"
  model_name: "models/recurrent_gemma_default"
