prompt_dir: 'LongAlign/Needle_test/prompts'
save_dir: 'LongAlign/Needle_test/pred'

model:
  model_provider: "Huggingface"  # "OpenAI", "Anthropic" or "Huggingface"
  model_name: "models/recurrent_gemma_default"
