eval:
  save_dir: results
parent_dir: NIAH/Needle_test/Jamba
pred:
  batch_size: 1
  model_path: "ai21labs/AI21-Jamba-Mini-1.6"
  model_type: Huggingface
  save_dir: pred
  sparsification:
    k:
    - 32
    metric: entropy
    prefill: false
  tokenizer_path: ai21labs/AI21-Jamba-Mini-1.6
prompt:
  context:
    interval: 10
    manually_select_list: null
    max_len: 4096
    min_len: 250
  document_depth:
    interval: 10
    interval_type: linear
    manually_select_list: null
    max_percent: 100
    min_percent: 0
  haystack_dir: ../PaulGrahamEssays
  is_base: false
  is_jrt: false
  needle: '

    The best thing to do in San Francisco is eat a sandwich and sit in Dolores Park
    on a sunny day.

    '
  retrieval_question: 'What is the best thing to do in San Francisco? Here is the
    most relevant sentence in the context:'
  save_dir: prompts
  tokenizer:
    model_name: ai21labs/AI21-Jamba-Mini-1.6
    tokenizer_type: Huggingface
vis:
  save_dir: vis
